version: 2.1
jobs:
  build:
    machine:
      image: cimg/base:current
    working_directory: /beliven-test
    steps:
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up --build -d